### ISSUE TITLE
lightbox content of popup coupon help disappears when using developer tools 

### ISSUE THREAD

**Issue by torvista** [mc12345678/zen-colorbox#22]
Chrome and Firefox on Windows.
If the developer tools window is open before the link on the coupon is clicked, the lightbox opens briefly with the content then reduces to a minimal size/has no content.
This does not occur with images on other pages.

**Comment by mc12345678** [comment]
Does github [issue about the unbalanced paragraph tag for Zencart](https://github.com/zencart/zencart/issues/2254) resolve this issue or is it unrelated?

**Comment by torvista** [comment]
Unrelated. I note that is it is a size thing. When the lightbox is open, as soon as you press F12 it jumps to a minimum size, the content is still there.
If the developer tools is in a separate window the lightbox works ok, so I don't think this is really of any importance., but it's here for reference.
