### ISSUE TITLE
lightbox infinite loading on a missing image file

### ISSUE THREAD

**Issue by torvista** [mc12345678/zen-colorbox#23]
If a product does not have an image defined, this is handled in 
includes/functions/extra_functions/zen_colorbox.php
with
`//auto replace with defined missing image
  
if ($src == DIR_WS_IMAGES and PRODUCTS_IMAGE_NO_IMAGE_STATUS == '1') {
    $src = DIR_WS_IMAGES . PRODUCTS_IMAGE_NO_IMAGE;
  }`

In an image IS defined, but is actually missing, the lightbox opens and shows the loading icon permanently.

I amended this to:
`  //auto replace with defined missing image

  if ( ($src == DIR_WS_IMAGES || !file_exists($src)) and PRODUCTS_IMAGE_NO_IMAGE_STATUS == '1') {
    $src = DIR_WS_IMAGES . PRODUCTS_IMAGE_NO_IMAGE;
  }`

Really the core code should display the no.picture.gif when an image is missing...

**Comment by mc12345678** [comment]
First question is if using an image handler, has the image handler already modified `$src` to point to a file that exists? If not then, the code below that point will not execute properly to point to the file that really exists when fed a file to be handled.

Another problem I see with testing against the existence of the file as relates to showing the no image file is the possibility of feeding other data into `$src` that would support testing the existence of files in the filesystem and getting the no image image.  I seem to recall that there had been a change in handling images a few years ago related to this aspect (additional images?), though I haven't recently looked into what specifically got changed to try to overcome the issue.

I'm hesitant about incorporating this type of "check" or correction based on the path not being properly fed.  

Would think that there should be some supported timer that could be used to provide an alternate image or disable the overlay if not loaded in a proper time period.

**Comment by torvista** [comment]
I won't get round to this...
https://www.zen-cart.com/showthread.php?225358-Missing-image-to-create-a-debug-log

**Comment by torvista** [comment]
I decided that first the issue needed to be fixed in the core code, then add-ons would work properly.
I needed to add the missing file check/replacement in both function zen_image and main_product_image, then the lightbox worked fine with the replacement image.
